language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - env: TARGET=thumbv6m-none-eabi
      rust: stable

    - env: TARGET=thumbv7m-none-eabi
      rust: stable

    - env: TARGET=thumbv7em-none-eabi
      rust: stable

    - env: TARGET=thumbv7em-none-eabihf
      rust: stable

    - env: TARGET=thumbv8m.base-none-eabi
      rust: stable

    - env: TARGET=thumbv8m.main-none-eabi
      rust: stable

    - env: TARGET=thumbv8m.main-none-eabihf
      rust: stable

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  email:
    on_success: never
